{
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module"
  },
  "rules": {
    "comma-dangle": ["error", "always-multiline"],
    "semi": ["error", "always"],
    "quotes": [2, "single"],
    "strict": [2, "never"],
    "indent": [2, "tab", { "SwitchCase": 1 }],
    "no-shadow": 0,
    "no-console": 0,
    "node/no-unsupported-features": [2, { "version": 6 }],
    "node/no-unpublished-require": 0,
    "node/no-deprecated-api": 0
  },
  "env": {
    "es6": true,
    "browser": true,
    "node": true
  },
  "plugins": ["node"],
  "extends": ["eslint:recommended", "plugin:node/recommended"]
}
